name: swift_service
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  smooth_page_indicator: ^1.2.0+3
  shared_preferences: ^2.3.1
  flutter_otp_text_field: ^1.1.3+2
  flutter_launcher_icons: ^0.13.1
  go_router: ^14.2.3
  carousel_slider: ^5.0.0
  dio: ^5.6.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  freezed: ^2.5.7
  auto_injector: ^2.0.5
  flutter_dotenv: ^5.1.0
  dartz: ^0.10.1
  flutter_spinkit: ^5.2.1
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_icons:
  image_path: "assets/images/logo.png" 
  android: true
  ios: true    



flutter:

  uses-material-design: true
  fonts:
  - family: Ubuntu
    fonts:
      - asset: assets/fonts/Ubuntu-Bold.ttf
        weight: 900
      - asset: assets/fonts/Ubuntu-Medium.ttf
        weight: 700
      - asset: assets/fonts/Ubuntu-Regular.ttf
        weight: 500
      - asset: assets/fonts/Ubuntu-Light.ttf
        weight: 300
  - family: Sf Pro
    fonts:
      - asset: assets/fonts/Sf-Pro-Display-Medium.ttf
        weight: 500
      
     
      

  
  assets:
    - assets/images/
    - assets/icons/

 